name: Ping composer

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /api/compose-run
        env:
          PING_URL: ${{ vars.PING_URL }}
        run: |
          if [ -z "$PING_URL" ]; then
            echo "Set repository variable PING_URL to your deployed URL (e.g., https://your-app.vercel.app/api/compose-run)" >&2
            exit 0
          fi
          curl -fsS "$PING_URL" || exit 1
